# Generated by Django 4.0.6 on 2022-07-11 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('bond_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, decimal_places=5, max_digits=19, null=True)),
                ('updated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('desk_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('cash', models.DecimalField(decimal_places=5, max_digits=19)),
                ('updated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FX',
            fields=[
                ('currency', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=5, max_digits=19)),
                ('updated', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('trader_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('desk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.desk')),
            ],
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('buy_sell', models.CharField(max_length=1)),
                ('quantity', models.IntegerField()),
                ('position', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=5, max_digits=19)),
                ('fx_rate', models.DecimalField(decimal_places=5, max_digits=19)),
                ('value', models.DecimalField(decimal_places=5, max_digits=19)),
                ('cash', models.DecimalField(decimal_places=5, max_digits=19)),
                ('met_exception', models.BooleanField(default=False)),
                ('exception_name', models.CharField(blank=True, choices=[('INSUFFICIENT_CASH', 'Insufficient Cash'), ('BOND_NOT_FOUND', 'Bond Not Found')], max_length=20, null=True)),
                ('bond_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bond')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('desk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.desk')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trader')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='trader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trader'),
        ),
        migrations.CreateModel(
            name='BondRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('bond_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bond')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('trader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trader')),
            ],
        ),
        migrations.AddField(
            model_name='bond',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fx'),
        ),
    ]
