# Generated by Django 4.0.6 on 2022-07-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventExceptionLog',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('exception_name', models.CharField(choices=[('INSUFFICIENT_CASH', 'Insufficient Cash'), ('BOND_NOT_FOUND', 'Bond Not Found')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='exception_name',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='met_exception',
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
