# Generated by Django 4.0.6 on 2022-07-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eventexceptionlog_remove_eventlog_exception_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventlog',
            old_name='book',
            new_name='book_id',
        ),
        migrations.RenameField(
            model_name='eventlog',
            old_name='trader',
            new_name='trader_id',
        ),
    ]
